### ISSUE TITLE
Nothing will be logged if message contains non-ascii characters

### ISSUE THREAD

**Issue by tom-englert** [pada57/serilog-sinks-influxdb#28]
A message with e.g. umlauts äöü does not crate any entry in influx.

**Comment by pada57** [comment]
This should not be link to escaping. Encoding not change by the sink itself as treating only string

**Comment by tom-englert** [comment]
Can you be more specific what you exactly mean by this?

**Comment by pada57** [comment]
i mean you linked commit [3594fc8](https://github.com/tom-englert/serilog-sinks-influxdb/commit/3594fc8729b557dabd3c1a37456240d2e3bbfe88) which is about escaping less characters but here you described no message if non-ascii characters. 

escaping with original code below was because in version 1.X i used a different lib than InfluxDbClient which was using API
this doesn't change original string 
`> System.Web.HttpUtility.JavaScriptStringEncode("äöü")
"äöü"`

sink code only deal with c# strings which doesn't change original encoding, encoding is more on influxdb side while storing in bucket or on source message being read from another source

**Comment by tom-englert** [comment]
This commit mentions both issues, since  the fix is in the same method, so GH linked it to both issues.

**Comment by tom-englert** [comment]
This is not an issue, must have been some side effect that made the tests fail.
