### ISSUE TITLE
Nice library!

### ISSUE THREAD

**Issue by suyashcjoshi** [pada57/serilog-sinks-influxdb#39]
This is very nice, have you tested it with InfluxDB v3 ?

**Comment by pada57** [comment]
Not tested. I could take a look but not in next days. Don't hesitate if you want to raise a PR

**Comment by suyashcjoshi** [comment]
I work at InfluxData and soon we will be releasing our open source 3.x version, currently it's available on the cloud and you can try for free without credit card or any payment (serverless). We would love to promote this awesome library in our newsletter etc but need to make sure it works for 3.0 version. Thanks and I'll see if I get time to test but no promise.

**Comment by pada57** [comment]
Great. Would try to have look before end of year. Is there a list of breaking changes with v2?

**Comment by tom-englert** [comment]
@suyashcjoshi You can just run the tests with the latest 3.x beta image instead of `influxdb:latest` to see if it still works correctly:
https://github.com/pada57/serilog-sinks-influxdb/blob/eacbae235d13d28ed8fe4ed2dc8b0910374f2b42/Tests/Serilog.Sinks.InfluxDB.Tests/InfluxDBTestContainer.cs#L98-L100

**Comment by pada57** [comment]
@suyashcjoshi  when do you plan to release an official image on docker hub ?
